"""add performance indexes for attendance and user batching

Revision ID: 09cd57cf0740
Revises: a8011396b238
Create Date: 2026-03-24 13:52:47.352027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cd57cf0740'
down_revision = 'a8011396b238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_batch_id'))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_timestamp'))

    # ### end Alembic commands ###
