"""add is_synced_to_sheets to users

Revision ID: 55554861d924
Revises: 09cd57cf0740
Create Date: 2026-03-31 11:12:18.126627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55554861d924'
down_revision = '09cd57cf0740'
branch_labels = None
depends_on = None


def upgrade():
    # ── approved_students: skip existing indexes, only add what's missing ──
    with op.batch_alter_table('approved_students', schema=None) as batch_op:
        pass  # ix_approved_students_registered already exists — nothing to do

    # ── attendance: skip existing indexes ──────────────────────────────────
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        pass  # ix_attendance_user_timestamp already exists — nothing to do

    # ── users: add the new column + new indexes only ───────────────────────
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_synced_to_sheets',
            sa.Boolean(),
            nullable=False,
            server_default='0'   # fills existing rows with False
        ))
        batch_op.create_index('ix_users_batch_role', ['batch_id', 'role'], unique=False)
        batch_op.create_index('ix_users_synced_to_sheets', ['is_synced_to_sheets', 'role'], unique=False)


def downgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_synced_to_sheets')
        batch_op.drop_index('ix_users_batch_role')
        batch_op.drop_column('is_synced_to_sheets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_synced_to_sheets')
        batch_op.drop_index('ix_users_batch_role')
        batch_op.drop_column('is_synced_to_sheets')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_user_timestamp')

    with op.batch_alter_table('approved_students', schema=None) as batch_op:
        batch_op.drop_index('ix_approved_students_registered')

    # ### end Alembic commands ###
