"""add holidays and batch exceptions tables

Revision ID: 6dd84eab2d09
Revises: 55554861d924
Create Date: 2026-04-14 22:51:38.503590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd84eab2d09'
down_revision = '55554861d924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index('ix_holidays_date', ['date'], unique=False)

    op.create_table('batch_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='fk_batch_exception_batch_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'date', name='unique_batch_exception_date')
    )
    with op.batch_alter_table('batch_exceptions', schema=None) as batch_op:
        batch_op.create_index('ix_batch_exceptions_batch_date', ['batch_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_exceptions', schema=None) as batch_op:
        batch_op.drop_index('ix_batch_exceptions_batch_date')

    op.drop_table('batch_exceptions')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index('ix_holidays_date')

    op.drop_table('holidays')
    # ### end Alembic commands ###
