"""add google_id to users, make password_hash nullable

Revision ID: 968040b1c41b
Revises: 6dd84eab2d09
Create Date: 2026-04-17 21:23:37.258652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968040b1c41b'
down_revision = '6dd84eab2d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
