"""remove qr_session_id from attendance

Revision ID: a623555b3e58
Revises: f755d9f0ad2c
Create Date: 2026-05-17 11:11:24.841525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a623555b3e58'
down_revision = 'f755d9f0ad2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_qr_session_id_fkey'), type_='foreignkey')
        batch_op.drop_column('qr_session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('attendance_qr_session_id_fkey'), 'qr_sessions', ['qr_session_id'], ['id'])

    # ### end Alembic commands ###
