"""add level_started_at to batches and student_level to attendance

Revision ID: a8011396b238
Revises: a67b4d596afe
Create Date: 2026-03-14 21:24:25.414902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8011396b238'
down_revision = 'a67b4d596afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_level', sa.String(length=50), nullable=True))

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_column('level_started_at')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('student_level')

    # ### end Alembic commands ###
