"""add student_devices and qr_sessions

Revision ID: e79313b3f87a
Revises: f08dc8f099af
Create Date: 2026-05-15 21:03:47.744854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79313b3f87a'
down_revision = 'f08dc8f099af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_sessions_token'), ['token'], unique=True)
        batch_op.create_index('ix_qr_sessions_token_expires', ['token', 'expires_at'], unique=False)

    op.create_table('student_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('pin_hash', sa.String(length=256), nullable=True),
    sa.Column('passkey_id', sa.String(length=256), nullable=True),
    sa.Column('trusted', sa.Boolean(), nullable=True),
    sa.Column('first_seen_ip', sa.String(length=45), nullable=True),
    sa.Column('last_seen_ip', sa.String(length=45), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passkey_id'),
    sa.UniqueConstraint('student_id', 'fingerprint_hash', name='uq_student_device')
    )
    with op.batch_alter_table('student_devices', schema=None) as batch_op:
        batch_op.create_index('ix_student_devices_fp', ['fingerprint_hash'], unique=False)
        batch_op.create_index('ix_student_devices_student', ['student_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_fp_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('qr_session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_attendance_device_fp_hash'), ['device_fp_hash'], unique=False)
        batch_op.create_foreign_key(None, 'qr_sessions', ['qr_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attendance_device_fp_hash'))
        batch_op.drop_column('qr_session_id')
        batch_op.drop_column('device_fp_hash')

    with op.batch_alter_table('student_devices', schema=None) as batch_op:
        batch_op.drop_index('ix_student_devices_student')
        batch_op.drop_index('ix_student_devices_fp')

    op.drop_table('student_devices')
    with op.batch_alter_table('qr_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_qr_sessions_token_expires')
        batch_op.drop_index(batch_op.f('ix_qr_sessions_token'))
        batch_op.drop_index(batch_op.f('ix_qr_sessions_expires_at'))

    op.drop_table('qr_sessions')
    # ### end Alembic commands ###
