"""initial

Revision ID: f08dc8f099af
Revises: 
Create Date: 2026-04-20 13:05:15.602072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08dc8f099af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('level_started_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index('ix_holidays_date', ['date'], unique=False)

    op.create_table('batch_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='fk_batch_exception_batch_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'date', name='unique_batch_exception_date')
    )
    with op.batch_alter_table('batch_exceptions', schema=None) as batch_op:
        batch_op.create_index('ix_batch_exceptions_batch_date', ['batch_id', 'date'], unique=False)

    op.create_table('batch_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='fk_batch_schedule_batch_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'weekday', name='unique_batch_weekday')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('is_synced_to_sheets', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='fk_user_batch_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_users_batch_role', ['batch_id', 'role'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index('ix_users_synced_to_sheets', ['is_synced_to_sheets', 'role'], unique=False)

    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='fk_absence_batch_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_student_absence_date')
    )
    op.create_table('approved_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.Column('registered_user_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='fk_approved_student_batch_id'),
    sa.ForeignKeyConstraint(['registered_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'name', name='unique_batch_student')
    )
    with op.batch_alter_table('approved_students', schema=None) as batch_op:
        batch_op.create_index('ix_approved_students_batch_lower_email', ['batch_id', sa.literal_column('lower(email)')], unique=True)
        batch_op.create_index('ix_approved_students_registered', ['is_registered'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('is_personal_time', sa.Boolean(), nullable=False),
    sa.Column('student_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_attendance_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('uix_user_level_date', ['user_id', sa.literal_column('DATE(timestamp)')], unique=True)

    op.create_table('blocked_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('attempted_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_attempts')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('uix_user_level_date')
        batch_op.drop_index('ix_attendance_user_timestamp')
        batch_op.drop_index(batch_op.f('ix_attendance_user_id'))
        batch_op.drop_index('ix_attendance_timestamp')

    op.drop_table('attendance')
    with op.batch_alter_table('approved_students', schema=None) as batch_op:
        batch_op.drop_index('ix_approved_students_registered')
        batch_op.drop_index('ix_approved_students_batch_lower_email')

    op.drop_table('approved_students')
    op.drop_table('absences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_synced_to_sheets')
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_batch_role')
        batch_op.drop_index(batch_op.f('ix_users_batch_id'))

    op.drop_table('users')
    op.drop_table('batch_schedules')
    with op.batch_alter_table('batch_exceptions', schema=None) as batch_op:
        batch_op.drop_index('ix_batch_exceptions_batch_date')

    op.drop_table('batch_exceptions')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index('ix_holidays_date')

    op.drop_table('holidays')
    op.drop_table('batches')
    # ### end Alembic commands ###
