"""add instructor_whitelist

Revision ID: f755d9f0ad2c
Revises: e79313b3f87a
Create Date: 2026-05-16 07:25:34.108451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f755d9f0ad2c'
down_revision = 'e79313b3f87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.Column('registered_user_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registered_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('instructor_whitelist', schema=None) as batch_op:
        batch_op.create_index('ix_instructor_whitelist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor_whitelist', schema=None) as batch_op:
        batch_op.drop_index('ix_instructor_whitelist_email')

    op.drop_table('instructor_whitelist')
    # ### end Alembic commands ###
